# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
print(np.show_config())

1.13.1
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/eneskemal/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/eneskemal/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/eneskemal/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/eneskemal/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/eneskemal/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/eneskemal/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    library_dirs = ['/home/eneskemal/anaconda3/lib']


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [4]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [5]:
type(Z[0][0]) 
# Float is 8 byte and in 10x10 matrix

numpy.float64

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
Z = np.arange(50)
print(Z)
print("Reversed:")
print(Z[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reversed:
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [11]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3,3,3))

array([[[ 0.13552594,  0.42459471,  0.50327222],
        [ 0.63689587,  0.60366062,  0.1735254 ],
        [ 0.58401838,  0.46179767,  0.00890724]],

       [[ 0.92867588,  0.74099897,  0.70837444],
        [ 0.69609238,  0.62920671,  0.78412256],
        [ 0.39415546,  0.14637581,  0.77419093]],

       [[ 0.67570355,  0.78939637,  0.74012604],
        [ 0.67856735,  0.54986613,  0.05247811],
        [ 0.4788105 ,  0.98487995,  0.42419387]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
Z = np.random.random((10,10))
print("Min Value: ", Z.min(), "Max Value: ", Z.max())

Min Value:  0.0018628300981 Max Value:  0.976158095902


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.random.random(30).mean()

0.55309906402107167

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
Z = np.ones((10,10))
Z[ 1:-1, 1:-1 ] = 0
Z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [19]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [24]:
0 * np.nan

nan

In [25]:
np.nan == np.nan

False

In [26]:
np.inf > np.nan

False

In [27]:
np.nan - np.nan

nan

In [28]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [34]:
np.diag(1+np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [35]:
np.diag(1+np.arange(10), k=-1)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0]])

In [36]:
np.diag(1+np.arange(5), k=3)

array([[0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [42]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [43]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [44]:
np.tile? # Help Function in JUpyter

In [47]:
print(np.tile(np.array([[0,1], [1,0]]), (4,4)) ) # Repeats the [[0,1], [1,0]] pattern

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [54]:
Z = np.random.random((5,5)) # Create 5x5 Matrix with Random Values
print(Z)
Zmax, Zmin = Z.max(), Z.min() # Find the max and min value in the matrix
Z = (Z - Zmin) / (Zmax-Zmin) # Normalize the matrix
print('='*60)
print(Z)

[[ 0.85111307  0.55458678  0.46593729  0.66248429  0.82233405]
 [ 0.96585402  0.78783155  0.63433064  0.02754984  0.23173961]
 [ 0.89341312  0.56962983  0.428789    0.54675893  0.56161308]
 [ 0.36658679  0.32428668  0.15301017  0.34913367  0.7245981 ]
 [ 0.5191527   0.14856316  0.49153301  0.11121597  0.62024213]]
[[ 0.87771455  0.56169092  0.4672125   0.67668296  0.84704324]
 [ 1.          0.81027211  0.64667814  0.          0.21761575]
 [ 0.92279593  0.57772309  0.42762163  0.55334838  0.56917922]
 [ 0.36132947  0.31624803  0.13370965  0.34272876  0.7428809 ]
 [ 0.52392696  0.12897024  0.49449121  0.08916739  0.63166328]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [57]:
np.ubyte? 
# Base class for numpy scalar types

In [58]:
# Assign scalar types to r,g,b,a
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

In [59]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [60]:
Z = np.dot( np.ones((5,3)), np.ones((3,2)) ) # Dot product of 2 matrix
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [61]:
# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2)) # @ dot product in Python 3.5 or above
print(Z)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [65]:
Z = np.arange(11)
Z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [67]:
print(sum(range(5),-1))

9


In [68]:
from numpy import *

In [69]:
print(sum(range(5),-1)) # Uses numpy's sum function

10


In [73]:
sum?

In [76]:
sum?

In [77]:
# -1 in the numpy's sum is probably for axis

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [93]:
Z = np.arange(5)
Z

array([0, 1, 2, 3, 4])

In [94]:
Z**Z

array([  1,   1,   4,  27, 256])

In [95]:
Z

array([0, 1, 2, 3, 4])

In [96]:
2 << Z >> 2

array([0, 1, 2, 4, 8])

In [97]:
Z <- Z

array([False, False, False, False, False], dtype=bool)

In [98]:
1j*Z

array([ 0.+0.j,  0.+1.j,  0.+2.j,  0.+3.j,  0.+4.j])

In [99]:
Z/1/1

array([ 0.,  1.,  2.,  3.,  4.])

In [100]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [102]:
np.array(0) / np.array(0)

/home/eneskemal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [103]:
np.array(0) // np.array(0)

/home/eneskemal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [104]:
np.array([np.nan]).astype(int).astype(float)

array([ -9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [105]:
Z = np.random.uniform(-10,+10,10)
Z

array([-0.55363626, -9.28785635,  5.41270618, -6.67327484,  4.31247688,
        5.37924395, -3.00570855, -2.09963569,  0.71849195, -5.48479175])

In [108]:
np.ceil(Z)

array([-0., -9.,  6., -6.,  5.,  6., -3., -2.,  1., -5.])

In [110]:
np.ceil(np.abs(Z))

array([  1.,  10.,   6.,   7.,   5.,   6.,   4.,   3.,   1.,   6.])

In [111]:
print(np.copysign(np.ceil(np.abs(Z)), Z)) # Copy the signs 

[ -1. -10.   6.  -7.   5.   6.  -4.  -3.   1.  -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [118]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
Z1

array([1, 5, 7, 2, 7, 7, 8, 9, 2, 3])

In [119]:
Z2

array([4, 3, 9, 3, 8, 2, 5, 7, 9, 5])

In [120]:
print(np.intersect1d(Z1,Z2)) # returns the Common values

[2 3 5 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [121]:
# Suicide mode on
defaults = np.seterr(all="ignore")



In [122]:
Z = np.ones(1) / 0

In [123]:
# Back to sanity
_ = np.seterr(**defaults)

In [124]:
Z = np.ones(1) / 0

/home/eneskemal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [125]:
np.sqrt(-1) == np.emath.sqrt(-1)

/home/eneskemal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [126]:
print("Yesterday:", np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print('Today:', np.datetime64('today', 'D'))
print('Tomorrow:', np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

Yesterday: 2017-08-27
Today: 2017-08-28
Tomorrow: 2017-08-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [127]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [128]:
# Initialize A, B, and C
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

In [134]:
# numpy's add, divide, negative, multiply, substract places the out vector without copy

In [129]:
np.add(A,B, out=B)

array([ 3.,  3.,  3.])

In [130]:
np.divide(A,2, out=A)

array([ 0.5,  0.5,  0.5])

In [131]:
np.negative(A, out=A)

array([-0.5, -0.5, -0.5])

In [132]:
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [135]:
Z = np.random.uniform(0,10,10)
Z

array([ 9.55978986,  9.80106571,  4.83527735,  0.44116042,  0.38808857,
        6.77245071,  9.17546349,  6.31056349,  5.26343087,  6.38817495])

In [136]:
print(Z - Z%1)

[ 9.  9.  4.  0.  0.  6.  9.  6.  5.  6.]


In [137]:
print(np.floor(Z))

[ 9.  9.  4.  0.  0.  6.  9.  6.  5.  6.]


In [138]:
print(np.ceil(Z)-1)

[ 9.  9.  4.  0.  0.  6.  9.  6.  5.  6.]


In [139]:
print(Z.astype(int))

[9 9 4 0 0 6 9 6 5 6]


In [140]:
print(np.trunc(Z))

[ 9.  9.  4.  0.  0.  6.  9.  6.  5.  6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [141]:
Z = np.zeros((5,5))
Z += np.arange(5) # += adds result of arange to each row
Z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [143]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=float, count=-1)
print(Z)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [144]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [146]:
Z = np.random.random(10)
Z

array([ 0.66182989,  0.07473277,  0.79758335,  0.42225699,  0.38910156,
        0.24073081,  0.34954447,  0.37711276,  0.6423541 ,  0.87637256])

In [147]:
Z.sort()
print(Z)

[ 0.07473277  0.24073081  0.34954447  0.37711276  0.38910156  0.42225699
  0.6423541   0.66182989  0.79758335  0.87637256]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [148]:
Z = np.arange(10)

In [149]:
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [156]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [157]:
A

array([1, 1, 0, 0, 0])

In [158]:
B

array([1, 1, 0, 1, 1])

In [159]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
np.allclose(A,B)

False

In [160]:
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [161]:
Z = np.zeros(10)
Z.flags.writeable = False

In [162]:
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [163]:
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [10]:
Z = np.random.random((10,2))
print(Z)

[[ 0.49412343  0.77244372]
 [ 0.47609593  0.49666215]
 [ 0.52991938  0.78732459]
 [ 0.49718126  0.1621428 ]
 [ 0.65903597  0.72575784]
 [ 0.94353762  0.78392125]
 [ 0.62879424  0.54244189]
 [ 0.76605721  0.40035463]
 [ 0.88379325  0.05101681]
 [ 0.480357    0.68751779]]


In [11]:
X,Y = Z[:,0], Z[:,1]

In [12]:
print(np.sqrt(X**2 + Y**2))

[ 0.91696633  0.68799755  0.94904929  0.52295267  0.98033303  1.22670118
  0.83043687  0.86436537  0.88526449  0.8387035 ]


In [13]:
print(np.arctan2(Y,X))

[ 1.00170409  0.80653718  0.97837827  0.3152483   0.83354274  0.69326026
  0.71180378  0.48157718  0.05766084  0.9609548 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [14]:
Z = np.random.random(10)
print(Z)

[ 0.8458833   0.24769364  0.02840159  0.46704784  0.42555378  0.73772389
  0.04562979  0.87192878  0.14512074  0.78860753]


In [15]:
Z.argmax()

7

In [16]:
Z[Z.argmax()] = 0 

In [17]:
print(Z)

[ 0.8458833   0.24769364  0.02840159  0.46704784  0.42555378  0.73772389
  0.04562979  0.          0.14512074  0.78860753]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [18]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

[[( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.)]
 [( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.)]
 [( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.)]
 [( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.)]
 [( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.)]]


In [19]:
print(Z['x'])

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [20]:
print(Z['y'])

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [21]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


In [22]:
print(Z['x'])

[[ 0.    0.25  0.5   0.75  1.  ]
 [ 0.    0.25  0.5   0.75  1.  ]
 [ 0.    0.25  0.5   0.75  1.  ]
 [ 0.    0.25  0.5   0.75  1.  ]
 [ 0.    0.25  0.5   0.75  1.  ]]


In [23]:
print(Z['y'])

[[ 0.    0.    0.    0.    0.  ]
 [ 0.25  0.25  0.25  0.25  0.25]
 [ 0.5   0.5   0.5   0.5   0.5 ]
 [ 0.75  0.75  0.75  0.75  0.75]
 [ 1.    1.    1.    1.    1.  ]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [24]:
X = np.arange(8)
print(X)

[0 1 2 3 4 5 6 7]


In [26]:
Y = X + 0.5
print(Y)

[ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5]


In [29]:
C = 1.0 / np.subtract.outer(X, Y)
print(C)

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


In [30]:
print(np.linalg.det(C))

3638.16363712


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [31]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


In [32]:
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-3.40282e+38
3.40282e+38
1.19209e-07
-1.79769313486e+308
1.79769313486e+308
2.22044604925e-16


#### 49. How to print all the values of an array? (★★☆)

In [33]:
np.set_printoptions(threshold=np.nan)
np.zeros((16,16))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [34]:
Z = np.arange(100)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [35]:
V = np.random.uniform(0,100)
print(V)

39.1454057865101


In [39]:
index = (np.abs(Z-V)).argmin()

In [40]:
print(Z[index])

39


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [41]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


In [42]:
print(Z['position'])

[( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.)
 ( 0.,  0.) ( 0.,  0.) ( 0.,  0.) ( 0.,  0.)]


In [43]:
print(Z['color'])

[( 0.,  0.,  0.) ( 0.,  0.,  0.) ( 0.,  0.,  0.) ( 0.,  0.,  0.)
 ( 0.,  0.,  0.) ( 0.,  0.,  0.) ( 0.,  0.,  0.) ( 0.,  0.,  0.)
 ( 0.,  0.,  0.) ( 0.,  0.,  0.)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)